### ISSUE TITLE
You don't have permission to access /apache.php

### ISSUE THREAD

**Issue by jmontoyaa** [mitchellkrogza/Travis-CI-for-Apache-For-Testing-Apache-and-PHP-Configurations#1]
In your build you have this messages at the end:

"You don't have permission to access /apache.php"

**Comment by mitchellkrogza** [comment]
That error is specific for my testing. 

If you look at the line above it tests a curl `curl -A "80legs" http://local.dev:80/apache.php` which should generate a 403 forbidden error as it is using my Apache Bad Bot Blocker script for testing - https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker so a user-agent called 80legs should of course be forbidden, hence I have the command line run the curl, look for a 403 and exit with a 0 and not a 1.

I wrote this container for pre-testing putting Travis into operation on my live repo's.

My example can be adjusted to do whatever you want it to do. I specifically built that container to handle testing my blocker and pushing out commits with tags and version numbering.
